services:
  game:
    image: dan4kl/game:latest
    container_name: arcade-vesel
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.game.rule=Host(`game.casatd.org`)"
      - "traefik.http.routers.game.entrypoints=web"
      - "traefik.http.services.game.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
